services:
  - type: web
    name: redradius-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 120 app.main:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_sXlonC0t1NfR@ep-wild-resonance-ax4c6fcb-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/backend:.

